name: Build Terraform Docker Image

on: 
  push:
  pull_request:

jobs:

  build-and-push-docker-image:
    name: Build AWS/Terraform/kubectl image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./terraform
          # Note: tags has to be all lower-case
          tags: |
            tacrocha/aws-terraform-kubectl:latest 
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
